### ISSUE TITLE
Group's head may grow without bound `panic: open /root/.celestia/data/cs.wal: invalid argument`

### ISSUE THREAD

**Issue by kim201212** [celestiaorg/celestia-app#1687]
### Summary of Bug

I got below ERR and panic my full node. 
The full node was running with light node.
And I can't restart the full node.

### Consensus Full Node
```
4:53AM ERR Group's head may grow without bound err="open /root/.celestia/data/cs.wal/wal: invalid argument" head=/root/.celestia/data/cs.wal/wal module=consensus wal=/root/.celestia/data/cs.wal/wal
panic: open /root/.celestia/data/cs.wal: invalid argument
```
### Light Node
```
2023-05-03T04:53:05.751Z    INFO    badger    v2@v2.2007.4/levels.go:1000    [Compactor: 0] Running compaction: {level:0 score:1 dropPrefixes:[]} for level: 0

2023-05-03T04:53:08.787Z    INFO    badger    v2@v2.2007.4/levels.go:962    LOG Compact 0->1, del 9 tables, add 6 tables, took 3.036601532s

2023-05-03T04:53:08.787Z    INFO    badger    v2@v2.2007.4/levels.go:1010    [Compactor: 0] Compaction for level: 0 DONE
2023-05-03T04:53:08.787Z    INFO    badger    v2@v2.2007.4/levels.go:1000    [Compactor: 0] Running compaction: {level:1 score:1.5620166510343552 dropPrefixes:[]} for level: 1

2023-05-03T04:53:09.857Z    INFO    badger    v2@v2.2007.4/levels.go:962    LOG Compact 1->2, del 2 tables, add 2 tables, took 1.069485454s

2023-05-03T04:53:09.857Z    INFO    badger    v2@v2.2007.4/levels.go:1010    [Compactor: 0] Compaction for level: 1 DONE
2023-05-03T04:53:09.857Z    INFO    badger    v2@v2.2007.4/levels.go:1000    [Compactor: 0] Running compaction: {level:1 score:1.2994030006229877 dropPrefixes:[]} for level: 1

2023-05-03T04:53:10.737Z    INFO    badger    v2@v2.2007.4/levels.go:962    LOG Compact 1->2, del 2 tables, add 2 tables, took 879.929182ms

2023-05-03T04:53:10.737Z    INFO    badger    v2@v2.2007.4/levels.go:1010    [Compactor: 0] Compaction for level: 1 DONE
2023-05-03T04:53:10.737Z    INFO    badger    v2@v2.2007.4/levels.go:1000    [Compactor: 0] Running compaction: {level:1 score:1.0367909409105778 dropPrefixes:[]} for level: 1

2023-05-03T04:53:13.165Z    INFO    badger    v2@v2.2007.4/levels.go:962    LOG Compact 1->2, del 6 tables, add 6 tables, took 2.427452404s
```
### When I restart, I saw the logs
```
panic: failed to initialize database: open /root/.celestia/data/snapshots/metadata.db/LOCK: invalid argument

goroutine 1 [running]:
github.com/celestiaorg/celestia-app/cmd/celestia-appd/cmd.NewAppServer({0x2d684e0, 0xc000dbcc60}, {0x2d779e8, 0xc000120028}, {0x0, 0x0}, {0x2d48380?, 0xc001050d00?})
	/root/git/celestia-app/cmd/celestia-appd/cmd/root.go:245 +0x905
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x2d875b8, 0xc0010647b0}, 0x0, {0x0, 0x0}, {0x2d7d318, ...}, ...}, ...)
	/usr/local/go/pkg/mod/github.com/celestiaorg/cosmos-sdk@v1.8.0-sdk-v0.46.7/server/start.go:293 +0x474
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc000fb4600?, {0xc000487140?, 0x0?, 0x2?})
	/usr/local/go/pkg/mod/github.com/celestiaorg/cosmos-sdk@v1.8.0-sdk-v0.46.7/server/start.go:143 +0x148
github.com/spf13/cobra.(*Command).execute(0xc000fb4600, {0xc000487120, 0x2, 0x2})
	/usr/local/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000f58900)
	/usr/local/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/usr/local/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/usr/local/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:961
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x1def180?, {0x22c8f21, 0x8}, {0xc0013dca20, 0x13})
	/usr/local/go/pkg/mod/github.com/celestiaorg/cosmos-sdk@v1.8.0-sdk-v0.46.7/server/cmd/execute.go:36 +0x20f
main.main()
	/root/git/celestia-app/cmd/celestia-appd/main.go:14 +0x38
```

### Version

`celestia-appd`(Consensus Full node) : `0.12.2`
`celestia`(Light node):
```
Semantic version: v0.9.1
Commit: b8c24bfd76784b4c0f1c2d19d67d0cd3776af556
Build Date: Tue May  2 10:12:00 UTC 2023
System version: amd64/linux
Golang version: go1.20.1
```

### Steps to Reproduce

Run Consensus Node with Light Node

### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by cmwaters** [comment]
Hey @kim201212, thanks for posting this bug. Do you happen to have the stack trace for the first panic you observed on the consensus node?

**Comment by kim201212** [comment]
> Hey @kim201212, thanks for posting this bug. Do you happen to have the stack trace for the first panic you observed on the consensus node?
> 
> Also was there any problem with light node itself?

It's like seeing it for the first time. It appears to be a disk mount issue with my cloud provider rather than an issue with `celestia-appd`. Thank you for the comment
