### ISSUE TITLE
(untyped float constant 31556952000000000) to type int

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#2120]
### Summary of Bug

```
error:
# github.com/celestiaorg/celestia-app/x/mint/types
../../go/pkg/mod/github.com/celestiaorg/celestia-app@v1.0.0-rc9/x/mint/types/constants.go:15:27: cannot convert NanosecondsPerSecond * SecondsPerMinute * MinutesPerHour * HoursPerDay * DaysPerYear (untyped float constant 31556952000000000) to type int
make: *** [Makefile:22: build] Fehler 1
```

### Version

main

### Steps to Reproduce

I think: attempt to build celestia-app on a 32 bit machine

### For Admin Use

- [X] Not duplicate issue
- [X] Appropriate labels applied
- [X] Appropriate contributors tagged
- [X] Contributor assigned/self-assigned

**Comment by jcstein** [comment]
tagging @waynewayner for more context and adding some here:

he is running into issue building on his arm32 machine. should it work on arm32? he tried to install it without modification to the makefile, but it built for amd64 instead of arm32. ideas?
error:

```
# github.com/celestiaorg/celestia-app/x/mint/types
../../go/pkg/mod/github.com/celestiaorg/celestia-app@v1.0.0-rc9/x/mint/types/constants.go:15:27: cannot convert NanosecondsPerSecond * SecondsPerMinute * MinutesPerHour * HoursPerDay * DaysPerYear (untyped float constant 31556952000000000) to type int
make: *** [Makefile:22: build] Fehler 1
```

his makefile:
```
## build: Build celestia-node binary.
build:
    @echo "--> Building Celestia"
    @GOOS=linux GOARCH=arm go build -o build/ ${LDFLAGS} ./cmd/celestia
.PHONY: build
```

**Comment by rootulp** [comment]
Thanks for reporting @WayneWayner ! This appears to be a celestia-app bug which should be fixed by #2121

**Comment by WayneWayner** [comment]
There is still a overflow issues on the latest commit: 

```
$ go get  github.com/celestiaorg/celestia-app@dec925336384241e55056937633018c64b2c0910
go: downloading github.com/celestiaorg/celestia-app v1.0.0-rc0.0.20230718175129-dec925336384
go: downloading google.golang.org/grpc v1.56.2
go: downgraded github.com/celestiaorg/celestia-app v1.0.0-rc9 => v1.0.0-rc0.0.20230718175129-dec925336384
go: upgraded google.golang.org/grpc v1.56.1 => v1.56.2
$ make build 
--> Building Celestia
# github.com/celestiaorg/celestia-app/x/mint/types
../../go/pkg/mod/github.com/celestiaorg/celestia-app@v1.0.0-rc0.0.20230718175129-dec925336384/x/mint/types/constants.go:15:29: NanosecondsPerSecond * SecondsPerYear (constant 31556952000000000 of type int) overflows int
# github.com/celestiaorg/celestia-app/pkg/square
../../go/pkg/mod/github.com/celestiaorg/celestia-app@v1.0.0-rc0.0.20230718175129-dec925336384/pkg/square/builder.go:138:40: b.Blobs[i].Blob.Namespace undefined (type "github.com/tendermint/tendermint/types".Blob has no field or method Namespace)
../../go/pkg/mod/github.com/celestiaorg/celestia-app@v1.0.0-rc0.0.20230718175129-dec925336384/pkg/square/builder.go:138:69: b.Blobs[j].Blob.Namespace undefined (type "github.com/tendermint/tendermint/types".Blob has no field or method Namespace)
# github.com/celestiaorg/celestia-app/test/util/testfactory
../../go/pkg/mod/github.com/celestiaorg/celestia-app@v1.0.0-rc0.0.20230718175129-dec925336384/test/util/testfactory/blob.go:83:78: blobs[i].Namespace undefined (type "github.com/tendermint/tendermint/types".Blob has no field or method Namespace)
../../go/pkg/mod/github.com/celestiaorg/celestia-app@v1.0.0-rc0.0.20230718175129-dec925336384/test/util/testfactory/blob.go:83:100: blobs[j].Namespace undefined (type "github.com/tendermint/tendermint/types".Blob has no field or method Namespace)
make: *** [Makefile:22: build] Fehler 1

```

**Comment by rootulp** [comment]
I'm trying to reproduce this error. Since I'm on a 64-bit machine, I explored getting a Digital Ocean droplet or EC2 instance with 32-bit architecture. However, it seems Digital Ocean and AWS no longer support 32-bit architectures.

So I'm running a Docker container with 

```
$ docker run --rm -it i686/ubuntu bash
```

and set up git and other dependencies. But now I'm trying to install Go and it seems either Go dropped support for the architecture I'm on or I installed it incorrectly:

```
root@69c2e7c189b3:~# tar -C /usr/local -xzf go1.20.6.linux-386.tar.gz
root@69c2e7c189b3:~# export PATH=$PATH:/usr/local/go/bin
root@69c2e7c189b3:~# go version
fatal: morestack on g0
runtime: newstack called from g=0x8c065a0
	m=0x8a4c460 m->curg=0x8c060f0 m->g0=0x8a4b980 m->gsignal=0x8c06000
runtime.funcMaxSPDelta({0x8952020, 0x8a143e0})
	/usr/local/go/src/runtime/symtab.go:1091 +0xee fp=0x8c32674 sp=0x8c32620 pc=0x809e20e
runtime.init.4()
	/usr/local/go/src/runtime/preempt.go:318 +0x3b fp=0x8c32688 sp=0x8c32674 pc=0x808109b
runtime.doInit(0x8a0d560)
	/usr/local/go/src/runtime/proc.go:6525 +0xf8 fp=0x8c327c4 sp=0x8c32688 pc=0x808fec8
runtime.main()
	/usr/local/go/src/runtime/proc.go:199 +0x129 fp=0x8c327f0 sp=0x8c327c4 pc=0x8082479
runtime.goexit()
	/usr/local/go/src/runtime/asm_386.s:1326 +0x1 fp=0x8c327f4 sp=0x8c327f0 pc=0x80b0801
SIGTRAP: trace trap
PC=fatal error: runtime: wrong goroutine in newstack
0x80b0672panic during panic
 m=0 sigcode=128

goroutine 0 [idle]:

runtime.abort()
	goroutine /usr/local/go/src/runtime/asm_386.s:821 +0x20 fp= [0x377392a0idle sp=0x3773929c pc=0x80b0672]:

runtime.throw({0x86688f6, 0x24})
runtime.morestackfatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: stack trace unavailable
runtime·unlock: lock count
fatal error: runtime·unlock: lock count
```

```
root@69c2e7c189b3:~# uname -m
i686
```

Do you have any tips on how I can repro the issues you're observing on 32-bit machines @WayneWayner ?

**Comment by WayneWayner** [comment]
I am using a x86_64 machine running linux (Ubuntu on Kernel 6.4.2) to cross compile to arm.

In my medium article about the kindle light node is a part which explains the cross compiling part:
https://medium.com/@waynewayner/how-light-is-your-light-node-running-celestia-on-an-ebook-reader-f6ca96691489 

```
# Install crosscompiler
sudo apt-get install gcc-arm-linux-gnueabi

# Edit makefile to compile for arm CPU
nano Makefile


## build: Build celestia-node binary.
build:
 @echo "--> Building Celestia"
 @GOOS=linux GOARCH=arm go build -o build/ ${LDFLAGS} ./cmd/celestia
.PHONY: build

# Build
make build

# Check version
build/celestia version

Semantic version: v0.9.5-dev
Commit: 2fa72c7199e5b93772a2c7e25141cfbd28f16a8e
Build Date: Mo 15. Mai 21:15:23 CEST 2023
System version: arm/linux
Golang version: go1.20.4
```
