### ISSUE TITLE
Negative coin amount causing panic in prepare proposal ante handler

### ISSUE THREAD

**Issue by cmwaters** [celestiaorg/celestia-app#2552]
### Summary of Bug

Snippet of the logs in mocha-4
```
2:34PM ERR CONSENSUS FAILURE!!! err=“negative coin amount” module=consensus stack=“goroutine 773 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x5e\[ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2()](http://ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2())\n\t/home/pops/go/pkg/mod/github.com/celestiaorg/celestia-core@v1.26.2-tm-v0.34.28/consensus/state.go:744 +0x46\npanic({0x20ba2a0?, 0xc0c9cb82f0?})\n\t/usr/local/go/src/runtime/panic.go:914 +0x21f\[ngithub.com/cosmos/cosmos-sdk/x/auth/ante.SetUpContextDecorator.AnteHandle.func1()](http://ngithub.com/cosmos/cosmos-sdk/x/auth/ante.SetUpContextDecorator.AnteHandle.func1())\n\t/home/pops/go/pkg/mod/github.com/celestiaorg/cosmos-sdk@v1.18.0-sdk-v0.46.14/x/auth/ante/setup.go:57 +0x1e5\npanic({0x20ba2a0?, 0xc0c9cb82f0?})\n\t/usr/local/go/src/runtime/panic.go:914 +0x21f\[ngithub.com/cosmos/cosmos-sdk/types.Coin.Sub(...)](http://ngithub.com/cosmos/cosmos-sdk/types.Coin.Sub(...))\n\t/home/pops/go/pkg/mod/github.com/celestiaorg/cosmos-sdk@v1.18.0-sdk-v0.46.14/types/coin.go:122\[ngithub.com/cosmos/cosmos-sdk/x/bank/keeper.BaseSendKeeper.subUnlockedCoins({{{0x2ec3500](http://ngithub.com/cosmos/cosmos-sdk/x/bank/keeper.BaseSendKeeper.subUnlockedCoins(%7B%7B%7B0x2ec3500), 0xc00194d060}, {0x2e97a98, 0xc00194d240}, {0x2ec4560, 0xc001331180}}, {0x2ec3500, 0xc00194d060}, {0x2ec4560, 0xc001331180}, ...}, ...)\n\t/home/pops/go/pkg/mod/github.com/celestiaorg/cosmos-sdk@v1.18.0-sdk-v0.46.14/x/bank/keeper/send.go:187 +0x731\[ngithub.com/cosmos/cosmos-sdk/x/bank/keeper.BaseSendKeeper.SendCoins({{{0x2ec3500](http://ngithub.com/cosmos/cosmos-sdk/x/bank/keeper.BaseSendKeeper.SendCoins(%7B%7B%7B0x2ec3500), 0xc00194d060}, {0x2e97a98, 0xc00194d240}, {0x2ec4560, 0xc001331180}}, {0x2ec3500, 0xc00194d060}, {0x2ec4560, 0xc001331180}, ...}, ...)\n\t/home/pops/go/pkg/mod/github.com/celestiaorg/cosmos-sdk@v1.18.0-sdk-v0.46.14/x/bank/keeper/send.go:136 +0xe5\[ngithub.com/cosmos/cosmos-sdk/x/bank/keeper.BaseKeeper.SendCoinsFromAccountToModule({{{{0x2ec3500](http://ngithub.com/cosmos/cosmos-sdk/x/bank/keeper.BaseKeeper.SendCoinsFromAccountToModule(%7B%7B%7B%7B0x2ec3500), 0xc00194d060}, {0x2e97a98, 0xc00194d240}, {0x2ec4560, 0xc001331180}}, {0x2ec3500, 0xc00194d060}, {0x2ec4560, 0xc001331180}, ...}, ...}, ...)\n\t/home/pops/go/pkg/mod/github.com/celestiaorg/cosmos-sdk@v1.18.0-sdk-v0.46.14/x/bank/keeper/keeper.go:362 +0x134\[ngithub.com/cosmos/cosmos-sdk/x/auth/ante.DeductFees({_](http://ngithub.com/cosmos/cosmos-sdk/x/auth/ante.DeductFees(%7B_), _}, {{0x2eb1970, 0x42458e0}, {0x2ec3490, 0xc0ba211ec0}, {{0x0, 0x0}, {0xc00089c7e7, 0x7}, ...}, ...}, ...)\n\t/home/pops/go/pkg/mod/github.com/celestiaorg/cosmos-sdk@v1.18.0-sdk-v0.46.14/x/auth/ante/fee.go:130 +0x18b\[ngithub.com/cosmos/cosmos-sdk/x/auth/ante.DeductFeeDecorator.checkDeductFee({{_](http://ngithub.com/cosmos/cosmos-sdk/x/auth/ante.DeductFeeDecorator.checkDeductFee(%7B%7B_), _}, {_, _}, {_, _}, _}, {{0x2eb1970, 0x42458e0}, {0x2ec3490, ...}, ...}, ...)\n\t/home/pops/go/pkg/mod/github.com/celestiaorg/cosmos-sdk@v1.18.0-sdk-v0.46.14/x/auth/ante/fee.go:106 +0x5b4\[ngithub.com/cosmos/cosmos-sdk/x/auth/ante.DeductFeeDecorator.AnteHandle({{_](http://ngithub.com/cosmos/cosmos-sdk/x/auth/ante.DeductFeeDecorator.AnteHandle(%7B%7B_), _}, {_, _}, {_, _}, _}, {{0x2eb1970, 0x42458e0}, {0x2ec3490, ...}, ...}, ...)\n\t/home/pops/go/pkg/mod/github.com/celestiaorg/cosmos-sdk@v1.18.0-sdk-v0.46.14/x/auth/ante/fee.go:61 +0x233\[ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1({{0x2eb1970](http://ngithub.com/cosmos/cosmos-sdk/types.ChainAnteDecorators.func1(%7B%7B0x2eb1970), 0x42458e0}, {0x2ec3490, 0xc0ba211ec0}, {{0x0, 0x0}, {0xc00089c7e7, 0x7}, 0x19a6c, {0x0, ...}, ...}, ...}, ...)\n\t/home/pops/go/pkg/mod/github.com/celestiaorg/cosmos-sdk@v1.18.0-sdk-v0.46.14/types/handler.go:40 +0x136\[ngithub.com/cosmos/cosmos-sdk/x/auth/ante.ConsumeTxSizeGasDecorator.AnteHandle({{_](http://ngithub.com/cosmos/cosmos-sdk/x/auth/ante.ConsumeTxSizeGasDecorator.AnteHandle(%7B%7B_), _}}, {{0x2eb1970, 0x42458e0}, {0x2ec3490, 0xc0ba211ec0}, {{0x0, 0x0}, {0xc00089c7e7, 0x7}, ...}, ...}, ...)\
```

### Version

v1.0.0-rc14 mostly

### Steps to Reproduce

g

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by evan-forbes** [comment]
I could recreate this bug by 
- start setting the time in the context in PrepareProposal
- creating a vesting account
- sending some funds to lower the account balance
- delegating some funds to a validator
- stop setting the time in the context in PrepareProposal
- sending some funds to lower the account balance

which could explain what we were seeing above. Validators that didn't yet upgrade to v1.0.0-rc16 on mocha would panic upon receiving a transaction from a vested account that had its balance lowered via delegating, because they were setting the time in `PrepareProposal` context to zero, which would result in their locked funds showing up as larger than their total balance, and therefore causing only that validator to panic.

**Comment by cmwaters** [comment]
Closing this as it has been resolved by https://github.com/celestiaorg/celestia-app/commit/9617549bce26e7517ee47d28727db6bfe0a895ef

**Comment by cmwaters** [comment]
Closing this as it has been resolved by https://github.com/celestiaorg/celestia-app/commit/9617549bce26e7517ee47d28727db6bfe0a895ef
