### ISSUE TITLE
Straggling node test

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#3297]
## Context

Spun out from https://github.com/celestiaorg/celestia-app/issues/2615

## Proposal

Manually test (can use knuu or Docker) that spins up multiple nodes:
- 1 node on v2 with 67% of voting power
- 1 node on v1

1. How does it fail? Does the failure / error make sense to a node operator
2. Figure out what the straggling node operator would have to do to upgrade from v1 to v2. Then provide that as clear instructions in the celestia-app v2 upgrade notes (inspired by Osmosis) because someone may fail to upgrade prior to the upgrade height on mainnet. Optionally we can add the upgrade nodes to https://docs.celestia.org/.

**Comment by rootulp** [comment]
I'm working on this in [this branch](https://github.com/rootulp/celestia-app/tree/rp/straggling-node-test). If a node fails to set their `--v2-upgrade-height` and the rest of the network upgrades, the straggling node hits:

```
2024-04-25 14:48:24 6:48PM ERR CONSENSUS FAILURE!!! err="+2/3 committed an invalid block: wrong Block.Header.Version. Expected {11 1}, got {11 2}" module=consensus stack="goroutine 214 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x64\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2()\n\t/go/pkg/mod/github.com/celestiaorg/celestia-core@v1.35.0-tm-v0.34.29/consensus/state.go:746 +0x44\npanic({0x1b91180?, 0x400153b240?})\n\t/usr/local/go/src/runtime/panic.go:770 +0x124\ngithub.com/tendermint/tendermint/consensus.(*State).finalizeCommit(0x400065ea88, 0x3)\n\t/go/pkg/mod/github.com/celestiaorg/celestia-core@v1.35.0-tm-v0.34.29/consensus/state.go:1637 +0xd30\ngithub.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit(0x400065ea88, 0x3)\n\t/go/pkg/mod/github.com/celestiaorg/celestia-core@v1.35.0-tm-v0.34.29/consensus/state.go:1606 +0x26c\ngithub.com/tendermint/tendermint/consensus.(*State).handleCompleteProposal(0x400065ea88, 0x3)\n\t/go/pkg/mod/github.com/celestiaorg/celestia-core@v1.35.0-tm-v0.34.29/consensus/state.go:2001 +0x2d8\ngithub.com/tendermint/tendermint/consensus.(*State).handleMsg(0x400065ea88, {{0x2b30a00, 0x400143e048}, {0x40002a61b0, 0x28}})\n\t/go/pkg/mod/github.com/celestiaorg/celestia-core@v1.35.0-tm-v0.34.29/consensus/state.go:856 +0x1c8\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0x400065ea88, 0x0)\n\t/go/pkg/mod/github.com/celestiaorg/celestia-core@v1.35.0-tm-v0.34.29/consensus/state.go:782 +0x2c4\ncreated by github.com/tendermint/tendermint/consensus.(*State).OnStart in goroutine 169\n\t/go/pkg/mod/github.com/celestiaorg/celestia-core@v1.35.0-tm-v0.34.29/consensus/state.go:391 +0x110\n"
2024-04-25 14:48:24 6:48PM INF service stop impl={"Logger":{}} module=consensus msg={} wal=/opt/data/cs.wal/wal
2024-04-25 14:48:24 6:48PM INF service stop impl={"Dir":"/opt/data/cs.wal","Head":{"ID":"wnBAFiU9z1aK:/opt/data/cs.wal/wal","Path":"/opt/data/cs.wal/wal"},"ID":"group:wnBAFiU9z1aK:/opt/data/cs.wal/wal","Logger":{}} module=consensus msg={} wal=/opt/data/cs.wal/wal
```

**Comment by rootulp** [comment]
I was able to get the straggling node to sync to the tip of the chain with:
```
celestia-appd tendermint unsafe-reset-all --home="${CELESTIA_HOME}"
```

and then re-starting the node with the upgrade height specified.

```
celestia-appd start \
--home="${CELESTIA_HOME}" \
--moniker="${MONIKER}" \
--p2p.persistent_peers=e3c592c0c2ad4b05cef3791456b0d6dd4da72ed2@core0:26656 \
--rpc.laddr=tcp://0.0.0.0:26657 \
--v2-upgrade-height 3
```

**Comment by rootulp** [comment]
Notably, I couldn't get the straggling node to sync to the tip of the chain with:

```
celestia-appd rollback --home="${CELESTIA_HOME}"
```

because after restarting the straggling node would log errors about peers

```
2024-04-25 15:21:56 7:21PM INF Error reconnecting to peer. Trying again addr={"id":"e3c592c0c2ad4b05cef3791456b0d6dd4da72ed2","ip":"172.21.0.5","port":26656} err="duplicate CONN<172.21.0.5:26656>" module=p2p tries=1
2024-04-25 15:21:58 7:21PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=0 numToDial=10
2024-04-25 15:21:58 7:21PM INF No addresses to dial. Falling back to seeds module=pex
2024-04-25 15:22:04 7:22PM INF Error reconnecting to peer. Trying again addr={"id":"e3c592c0c2ad4b05cef3791456b0d6dd4da72ed2","ip":"172.21.0.5","port":26656} err="duplicate CONN<172.21.0.5:26656>" module=p2p tries=2
2024-04-25 15:22:05 7:22PM ERR SendTimeout module=blockchain peer=e3c592c0c2ad4b05cef3791456b0d6dd4da72ed2 reason="peer did not send us anything" timeout=15000
2024-04-25 15:22:11 7:22PM INF Error reconnecting to peer. Trying again addr={"id":"e3c592c0c2ad4b05cef3791456b0d6dd4da72ed2","ip":"172.21.0.5","port":26656} err="duplicate CONN<172.21.0.5:26656>" module=p2p tries=3
2024-04-25 15:22:17 7:22PM INF Error reconnecting to peer. Trying again addr={"id":"e3c592c0c2ad4b05cef3791456b0d6dd4da72ed2","ip":"172.21.0.5","port":26656} err="duplicate CONN<172.21.0.5:26656>" module=p2p tries=4
2024-04-25 15:22:24 7:22PM INF Error reconnecting to peer. Trying again addr={"id":"e3c592c0c2ad4b05cef3791456b0d6dd4da72ed2","ip":"172.21.0.5","port":26656} err="duplicate CONN<172.21.0.5:26656>" module=p2p tries=5
```

**Comment by rootulp** [comment]
> How does it fail? Does the failure / error make sense to a node operator

The error isn't the most legible but we can add it to an FAQ in the docs (likely on https://docs.celestia.org/nodes/validator-node)
