### ISSUE TITLE
Unable to restart application

### ISSUE THREAD

**Issue by cmwaters** [celestiaorg/celestia-app#3354]
Came across this problem when restarting the application on `main`:

```
3:05PM INF starting node with ABCI Tendermint in-process
3:05PM INF service start impl=multiAppConn module=proxy msg={}
3:05PM INF service start connection=query impl=localClient module=abci-client msg={}
3:05PM INF service start connection=snapshot impl=localClient module=abci-client msg={}
3:05PM INF service start connection=mempool impl=localClient module=abci-client msg={}
3:05PM INF service start connection=consensus impl=localClient module=abci-client msg={}
3:05PM INF service start impl=EventBus module=events msg={}
3:05PM INF service start impl=PubSub module=pubsub msg={}
3:05PM INF service start impl=IndexerService module=txindex msg={}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1026274b6]

goroutine 9 [running]:
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).createQueryContext(_, _, _)
	/Users/callum/Developer/go/pkg/mod/github.com/celestiaorg/cosmos-sdk@v1.21.0-sdk-v0.46.16/baseapp/abci.go:716 +0x1f6
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Info(0xc00026ad20, {{0x78?, 0x1030029e5?}, 0x0?, 0x0?})
	/Users/callum/Developer/go/pkg/mod/github.com/celestiaorg/cosmos-sdk@v1.21.0-sdk-v0.46.16/baseapp/abci.go:134 +0xe5
github.com/celestiaorg/celestia-app/v2/app.(*App).Info(0xc0010ea008, {{0x103724bfc?, 0x10?}, 0xc000099b08?, 0xc000791930?})
	/Users/callum/Developer/go/src/github.com/celestiaorg/celestia-app/app/app.go:500 +0x56
github.com/tendermint/tendermint/abci/client.(*localClient).InfoSync(0xc001bacea0, {{0x103724bfc?, 0x1?}, 0xc0011058d0?, 0x101b506bb?})
	/Users/callum/Developer/go/pkg/mod/github.com/celestiaorg/celestia-core@v1.35.0-tm-v0.34.29/abci/client/local_client.go:250 +0x109
github.com/tendermint/tendermint/proxy.(*appConnQuery).InfoSync(0xc0002b5400?, {{0x103724bfc?, 0xc000791920?}, 0x44d9000?, 0x106b32708?})
	/Users/callum/Developer/go/pkg/mod/github.com/celestiaorg/celestia-core@v1.35.0-tm-v0.34.29/proxy/app_conn.go:170 +0x23
github.com/tendermint/tendermint/consensus.(*Handshaker).HandshakeWithContext(0xc001105cd8, {0x104954d58, 0x105dee600}, {0x10496b770, 0xc0013c2d00})
	/Users/callum/Developer/go/pkg/mod/github.com/celestiaorg/celestia-core@v1.35.0-tm-v0.34.29/consensus/replay.go:250 +0x7a
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(...)
	/Users/callum/Developer/go/pkg/mod/github.com/celestiaorg/celestia-core@v1.35.0-tm-v0.34.29/consensus/replay.go:243
github.com/tendermint/tendermint/node.doHandshake({_, _}, {_, _}, {{{0xb, 0x1}, {0xc000804538, 0x7}}, {0xc000804570, 0x8}, ...}, ...)
	/Users/callum/Developer/go/pkg/mod/github.com/celestiaorg/celestia-core@v1.35.0-tm-v0.34.29/node/node.go:337 +0x1aa
github.com/tendermint/tendermint/node.NewNode(0xc000823e00, {0x104949640, 0xc000139360}, 0xc000791010, {0x1049330a0, 0xc0001234d0}, 0xc001107980, 0x104925898, 0xc001107970, {0x104954b60, ...}, ...)
	/Users/callum/Developer/go/pkg/mod/github.com/celestiaorg/celestia-core@v1.35.0-tm-v0.34.29/node/node.go:831 +0x6ab
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x104977b08, 0xc0013ecb10}, 0x0, {0x0, 0x0}, {0x10496f020, ...}, ...}, ...)
	/Users/callum/Developer/go/pkg/mod/github.com/celestiaorg/cosmos-sdk@v1.21.0-sdk-v0.46.16/server/start.go:301 +0x745
github.com/cosmos/cosmos-sdk/server.StartCmd.func2.2()
	/Users/callum/Developer/go/pkg/mod/github.com/celestiaorg/cosmos-sdk@v1.21.0-sdk-v0.46.16/server/start.go:147 +0x45
github.com/cosmos/cosmos-sdk/server.wrapCPUProfile.func2()
	/Users/callum/Developer/go/pkg/mod/github.com/celestiaorg/cosmos-sdk@v1.21.0-sdk-v0.46.16/server/start.go:535 +0x23
created by github.com/cosmos/cosmos-sdk/server.wrapCPUProfile in goroutine 1
	/Users/callum/Developer/go/pkg/mod/github.com/celestiaorg/cosmos-sdk@v1.21.0-sdk-v0.46.16/server/start.go:534 +0x23f
```

Looks like it has to do with creating the query context in `Info`

_Originally posted by @cmwaters in https://github.com/celestiaorg/celestia-app/issues/3167#issuecomment-2066561818_

**Comment by rootulp** [comment]
I just hit this while trying to use https://github.com/ninabarbakadze/celestia-app/tree/nina/versioned-middleware to sync from genesis on a Scaleway instance but I don't expect the issue to be unique to that branch 😢

**Comment by rach-id** [comment]
I confirm I am hitting it too. Apparently this commit is causing it: https://github.com/celestiaorg/celestia-app/commit/9db2f8b8bffe3dd1dd4eaf7d9b1d38afb71a193a
